services:
  db:
    image: postgres:latest
    restart: always  # Убедитесь, что база данных всегда перезапускается
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1988
      POSTGRES_DB: knitty
    ports:
      - "5434:5432"  # Порт для доступа к базе данных с хоста
    volumes:
      - db_data:/var/lib/postgresql/data  # Персистентный том для базы данных

  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/api-service"]
    image: knitti-api-service:latest
    environment:
      - DATABASE_HOST=db  # Используй имя контейнера базы данных
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1988
      - DATABASE_NAME=knitty
      - SERVER_PORT=8080  # Убедитесь, что ваш API слушает на этом порту
      - LOGGING_LEVEL=info
      - LOGGING_FILE=logs/app.log
      - LOGGING_MAX_SIZE=10
      - LOGGING_MAX_BACKUPS=5
      - LOGGING_MAX_AGE=30
      - LOGGING_COMPRESS=true
      - TELEGRAM_TOKEN=7434671523:AAEq_bG153U1P-5iAlRxd1uJwu9ESv4O8P4
    ports:  # Добавленная секция
      - "8080:8080"  # Перенаправление порта 8080
    depends_on:  # Убедитесь, что api-service не запускается, пока база данных не будет готова
      - db

  bot-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/bot-service"]
    image: knitti-bot-service:latest
    environment:
      - TELEGRAM_TOKEN=7434671523:AAEq_bG153U1P-5iAlRxd1uJwu9ESv4O8P4
      - LOGGING_LEVEL=info
      - LOGGING_FILE=logs/app.log
      - LOGGING_MAX_SIZE=10
      - LOGGING_MAX_BACKUPS=5
      - LOGGING_MAX_AGE=30
      - LOGGING_COMPRESS=true
    depends_on:  # Убедитесь, что bot-service тоже ждет базу данных
      - db

volumes:
  db_data:  # Определите том здесь
