telegram:
  token: "7434671523:AAEq_bG153U1P-5iAlRxd1uJwu9ESv4O8P4"

logging:
  level: "info" # Можно также использовать "debug", "warn", "error"
  file: "logs/app.log" # Имя файла для логов
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: true

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "1988"
  dbname: "knitty"
  sslmode: "disable"

server:
  port: "8080"
